name: wordpress_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  flutter_html: ^2.1.1
  url_launcher: ^6.0.9
  cached_network_image: ^3.1.0
  shimmer: ^2.0.0
  share: ^2.0.1 
  persistent_bottom_nav_bar: ^4.0.2
  font_awesome_flutter: ^9.1.0
  google_fonts:


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/